# Generated by Django 3.2.3 on 2021-11-17 04:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account_detail',
            fields=[
                ('account_number', models.BigIntegerField(primary_key=True, serialize=False)),
                ('employee_id', models.CharField(default='EMP0000000', max_length=10)),
                ('bankname', models.CharField(default='XYZ', max_length=50)),
                ('IFSC_code', models.CharField(default='XYZ', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Administrator',
            fields=[
                ('administrator_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('name', models.CharField(default='XYZ', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Allowance',
            fields=[
                ('employee_id', models.CharField(default='EMP0000000', max_length=10, primary_key=True, serialize=False)),
                ('bonus', models.IntegerField()),
                ('amount_of_allowances', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('employee_id', models.CharField(default='EMP0000000', max_length=10, primary_key=True, serialize=False)),
                ('working_hours', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Deduction',
            fields=[
                ('employee_id', models.CharField(default='EMP0000000', max_length=10, primary_key=True, serialize=False)),
                ('provident_fund', models.IntegerField()),
                ('ammount_of_deduction', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('department_id', models.CharField(default='DEPT202100', max_length=10, primary_key=True, serialize=False)),
                ('department_name', models.CharField(default='XYZ', max_length=30, null=True)),
                ('department_manager', models.CharField(default='ABCD', max_length=30, null=True)),
                ('salary_range', models.CharField(default='0000-0000', max_length=30, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='XYZ', max_length=30, null=True)),
                ('last_name', models.CharField(default='XYZ', max_length=30, null=True)),
                ('email', models.CharField(default='XYZ@XYZ.XYZ', max_length=30, null=True)),
                ('gender', models.CharField(default='MALE', max_length=10, null=True)),
                ('dob', models.DateField(null=True)),
                ('joining_date', models.DateField(null=True)),
                ('department_id', models.CharField(default='DEPT202100', max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Employee_address',
            fields=[
                ('employee_id', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('pincode', models.CharField(default='000000', max_length=6)),
                ('state', models.CharField(default='XYZ', max_length=50)),
                ('city', models.CharField(default='XYZ', max_length=50)),
                ('street', models.CharField(default='XYZ', max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_id', models.CharField(default='DEP0000000', max_length=10)),
                ('leave_date', models.DateField(default=datetime.datetime.now)),
                ('reason', models.CharField(default='XYZ', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('employee_id', models.CharField(default='EMP0000000', max_length=10, primary_key=True, serialize=False)),
                ('username', models.CharField(default='XYZ', max_length=20)),
                ('password', models.CharField(default='XYZ', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Phone_number',
            fields=[
                ('employee_id', models.CharField(default='EMP0000000', max_length=10)),
                ('phone_number', models.BigIntegerField(default='000000000000', primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('employee_id', models.CharField(default='EMP0000000', max_length=10, primary_key=True, serialize=False)),
                ('department_id', models.CharField(default='DEP0000000', max_length=10)),
                ('basic_salary', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('transaction_id', models.CharField(default='TRAN000000', max_length=10, primary_key=True, serialize=False)),
                ('employee_id', models.CharField(default='EMP0000000', max_length=10)),
                ('net_salary', models.IntegerField()),
                ('account_detail', models.BigIntegerField()),
                ('transaction_date', models.DateField()),
            ],
        ),
    ]
