# Generated by Django 3.2.3 on 2021-11-18 15:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('SMS', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee_address',
            name='pincode',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account_detail',
        ),
        migrations.AddField(
            model_name='transaction',
            name='account_number',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='SMS.account_detail'),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='account_number',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='account_detail',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.employee'),
        ),
        migrations.AlterField(
            model_name='allowance',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SMS.employee'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SMS.employee'),
        ),
        migrations.AlterField(
            model_name='deduction',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SMS.employee'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.department'),
        ),
        migrations.AlterField(
            model_name='employee_address',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SMS.employee'),
        ),
        migrations.AlterField(
            model_name='leave',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.employee'),
        ),
        migrations.AlterField(
            model_name='login',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SMS.employee'),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.employee'),
        ),
        migrations.AlterField(
            model_name='phone_number',
            name='phone_number',
            field=models.BigIntegerField(default=0, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salary',
            name='department_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.department'),
        ),
        migrations.AlterField(
            model_name='salary',
            name='employee_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='SMS.employee'),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='employee_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SMS.employee'),
        ),
    ]
